### ISSUE TITLE
Haystack with devcontainer extension is broken

### ISSUE THREAD

**Issue by olemd** [AkshaySG14/haystack-public#34]
Perhaps not unexpected since haystack isn't really vscode, but installing the devcontainer extension results in 

```
[6274 ms] Installing VS Code Server for commit cc102f3a62bd35f39ed059b99c5cce90e50a16e2
[6277 ms] Start: Downloading VS Code Server
[6278 ms] cc102f3a62bd35f39ed059b99c5cce90e50a16e2 linux-x64 stable
[6599 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:cc102f3a62bd35f39ed059b99c5cce90e50a16e2/server-linux-x64/stable): HTTP 404 - Not Found
[6599 ms] Retrying to download VS Code Server.
[6709 ms] Error: Server returned 404
    at a (vscode-file://vscode-app/tmp/.mount_haystaUxkNYo/usr/share/haystack-editor/resources/app/out/vs/workbench/workbench.desktop.main.js:693:43685)
    at k.download (vscode-file://vscode-app/tmp/.mount_haystaUxkNYo/usr/share/haystack-editor/resources/app/out/vs/workbench/workbench.desktop.main.js:694:1768)
```

which is … suboptimal.

**Comment by AkshaySG14** [comment]
Unfortunately we haven't gotten around to fixing the devcontainer extension. This is definitely on our list of things to fix!
