### ISSUE TITLE
Unable to connect to WSL Target 

### ISSUE THREAD

**Issue by equalsgibson** [AkshaySG14/haystack-public#7]
## Expectations

After installing Haystack Editor on Windows 11, I should be able to connect the editor to the same WSL Targets that I am successfully able to connect to with VSCode

## Reality

After installing the Haystack Editor, the WSL Option is not present as the WSL extension is not installed.  

After installing the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) manually (as [per the FAQ](https://haystackeditor.com/#faq)), I am presented with a new error that I am unable to resolve:

![image](https://github.com/user-attachments/assets/e9348301-bae1-47c0-93f3-d5f5cbb7be17)

The terminal output from WSL is below:  

```bash
[2024-08-23 10:49:55.992] Extension version: 0.88.2
[2024-08-23 10:49:55.992] L10N bundle: undefined
[2024-08-23 10:49:55.994] authorityHierarchy: wsl+Ubuntu
[2024-08-23 10:49:55.994] WSL extension activating for a local WSL instance
[2024-08-23 10:49:55.996] Resolving wsl+Ubuntu, resolveAttempt: 1
[2024-08-23 10:49:55.996] NodeExecServer run: C:\Windows\System32\wsl.exe --status
[2024-08-23 10:49:56.044] WSL feature installed: true (wsl --status)
[2024-08-23 10:49:56.044] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose
[2024-08-23 10:49:56.085] 4 distros found
[2024-08-23 10:49:56.086] Starting VS Code Server inside WSL (wsl2)
[2024-08-23 10:49:56.086] Windows build: 22631. Multi distro support: available. WSL path support: enabled
[2024-08-23 10:49:56.086] Scriptless setup: false
[2024-08-23 10:49:56.087] No shell environment set or found for current distro.
[2024-08-23 10:49:56.190] WSL daemon log file: 
[2024-08-23 10:49:56.193] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2024-08-23 11:01:42.103] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose
[2024-08-23 11:01:42.174] 4 distros found
```  

The error from the Haystack Editor is here:  

```bash
2024-08-23 12:03:01.625 [error] VSCode Client (c:\Users\cagib\Downloads\Haystack+Editor+Windows\Haystack Editor Windows\resources\app) does not define a quality.: CodeExpectedError: VSCode Client (c:\Users\cagib\Downloads\Haystack+Editor+Windows\Haystack Editor Windows\resources\app) does not define a quality.
    at ee.rb (vscode-file://vscode-app/c:/Users/cagib/Downloads/Haystack+Editor+Windows/Haystack%20Editor%20Windows/resources/app/out/vs/workbench/workbench.desktop.main.js:2970:26928)
    at async ee.qb (vscode-file://vscode-app/c:/Users/cagib/Downloads/Haystack+Editor+Windows/Haystack%20Editor%20Windows/resources/app/out/vs/workbench/workbench.desktop.main.js:2970:26184)
    at async ee.Ob (vscode-file://vscode-app/c:/Users/cagib/Downloads/Haystack+Editor+Windows/Haystack%20Editor%20Windows/resources/app/out/vs/workbench/workbench.desktop.main.js:2972:4057)
    at async ee.jb (vscode-file://vscode-app/c:/Users/cagib/Downloads/Haystack+Editor+Windows/Haystack%20Editor%20Windows/resources/app/out/vs/workbench/workbench.desktop.main.js:2970:23585)
```

## Steps to Reproduce

1. Uninstall & reinstall the latest version of Haystack Editor
1. Install the official WSL Extension from VSCode Marketplace (if not already installed)  
1. Attempt to connect to a WSL target

## Generic Info  
**Operating System:** 
Windows 11 
**Haystack Version:** 
1.90.0.0
**WSL Target OS:**     
Ubuntu 22.04
**WSL Target Info:**  
```bash
cgibson@wsl-ubuntuNexus:~$ uname -r
5.15.153.1-microsoft-standard-WSL2

cgibson@wsl-ubuntuNexus:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by AkshaySG14** [comment]
Thank you for the incredibly detailed report. Will work on this now.

**Comment by AkshaySG14** [comment]
Could you try redownloading Haystack, uninstalling the current WSL extension, and then downloading the WSL extension from the extension store and retrying this out?

**Comment by seneaLL** [comment]
> Could you try redownloading Haystack, uninstalling the current WSL extension, and then downloading the WSL extension from the extension store and retrying this out?

This doesn't help, the error doesn't go anywhere

**Comment by seneaLL** [comment]
https://github.com/user-attachments/assets/57194280-a6e9-4091-93f2-5f628d3eb0d5

**Comment by AkshaySG14** [comment]
Sorry for the frustration. I managed to repro on my end and am troubleshooting this now.

**Comment by AkshaySG14** [comment]
OK this should finally be fixed. Please download the newest version of Haystack (v 0.16) off the website and LMK if this doesn't work!

**Comment by AkshaySG14** [comment]
Reopened due to an error with installing the extension (v0.88.0).

**Comment by AkshaySG14** [comment]
For any folks in the future who encounter issues with installing 0.88.0, please contact me for help!
